---
output: 
  html_document
  

params:
  modelName: "perm.mod.1"
  mapName: "Perm1"
  rootDir: "X:/3_Land_suitability/0_Working/Uta/Roper"
  maxpixels: 100000
  srcPath: 'X:/3_Land_suitability/0_Working/Uta/Roper/Scripts/RandomForestUtils_V3.R'
--- 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

<style type="text/css">
.table {

    width: 20%;
    font-size:	10px;

}
</style>

## ROWRA Model Summary - `r params$attribute`
Report generated by `r Sys.getenv("USERNAME")` on `r date()`

## Maps



```{r Load Stuff, comment=NA, fig.height=7, fig.width=7, warning=F, echo=FALSE} 
library(raster)
library(rasterVis)
library(ranger)
library(knitr)
library(RColorBrewer)
library(randomcoloR)

source(srcPath)


#cat(paste0('Report generated by ', Sys.getenv("USERNAME"), ' on ', date()))


  modelPath <- paste0(rootDir, '/Models/', params$modelName, '.rds' )
model <- readRDS(modelPath) 
#print(paste0(params$rootDir, '/', params$attribute, '_', params$catchment, '.tif'))
```
```{r ROWRA Maps, comment=NA, fig.height=7, fig.width=7, warning=F} 
if(model$forest$treetype == 'Classification')
  {
    r <- as.factor(raster(paste0(params$rootDir, '/Maps/', params$mapName, '/', params$mapName, '.tif')))

    n <-length(unlist(levels(r)))
    my_cols <- distinctColorPalette(n)
    r <- ratify(r)
    rat <- levels(r)[[1]]
    if(is.number(model$forest$levels))
    {
      
      newrat <- data.frame("ID" = rat, "Category" = rat)
      colnames(newrat) <- c('ID', 'Category')
      levels(r) <- newrat
      levelplot(r, col.regions = my_cols, main =paste0(params$mapName), maxpixels=maxpixels)
    }else{
      t <- getRasterDecodes(model)
      newrat <- merge(rat, t, by.x = "ID", by.y = "RID")
      colnames(newrat) <- c('ID', 'Category')
      levels(r) <- newrat
      levelplot(r, col.regions = my_cols, main =paste0(params$mapName), maxpixels=maxpixels)
    }
  }else{
    r <- raster(paste0(params$rootDir, '/Maps/', params$mapName, '/', params$mapName, '.tif'))

    plot(r, main =paste0(params$mapName), maxpixels=maxpixels)
  }

cat(paste0(params$rootDir, '/', params$mapName, '.tif'))

modelType <- model$treetype

if(modelType == 'Classification'){

  if(!is.number(model$forest$levels))
    {
      kable(getRasterDecodes(model), col.names = c('Raster Value','Category'), row.names = F, caption = 'Raster Categories', align = 'c')
    }

}

###_CI.tif for categorical, _CoV.tif for continuous variables
r1 <- raster(paste0(params$rootDir, '/Maps/', params$mapName, '/', params$mapName,  '_CI.tif'))
plot(r1, main = paste0('Uncertainty for ', params$mapName), maxpixels=maxpixels)
cat(paste0(params$rootDir, '/', params$mapName, '_Uncert.tif'))


if(model$treetype == 'Classification'){
  
  barplot(r, main=paste0(params$mapName,  '- Value Counts'))
  
}else{
  
  d <- density(r)
  polygon(d, col="darkgreen", border="darkgreen")
  
}
  
```

### Model Statistics

```{r ROWRA Model Summary, comment=NA, fig.height=7, fig.width=7} 

summariseRFModel(modelPath)



#paste0("Model Path : ", params$modelPath)
#model 
#print(params$modelPath)
model$variable.importance[order(model$variable.importance, decreasing = TRUE)]

```